version: "3"

services:
  # db:
  #   image: postgres:11
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgresql-data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=test_db
  #   networks:
  #     - local-net
  web:
    build: .
    # command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - local-net

  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
  #     - PGADMIN_DEFAULT_PASSWORD=admin
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - db
  #   networks:
  #     - local-net

  db:
    hostname: db
    container_name: db
    build: ./mysql
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: sample_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql 
    networks:
      - local-net


volumes:
  # postgresql-data:
  #   driver: local

  mysql-data:
    driver: local
networks:
  local-net:
    driver: bridge